apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: movie-app
  template:
    metadata:
      labels:
        app: movie-app
    spec:
      containers:
      - name: movie-app
        image:  mokagema/demo-image-test:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: uri
